source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XMSegmentedControl_Example', :exclusive => true do
  pod "XMSegmentedControl", :path => "../"
end

target 'XMSegmentedControl_Tests', :exclusive => true do
  pod "XMSegmentedControl", :path => "../"

  
end
