source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XMSegmentedControl_Example' do
  pod "XMSegmentedControl", :path => "../"
end

target 'XMSegmentedControl_Tests' do
  pod "XMSegmentedControl", :path => "../"

end
